
COMPILER = clang++
FLAGS = --std=c++98 -Wall -Wextra -Werror


vector:
	@$(COMPILER) $(FLAGS)	my_vector_tests.cpp -o vector.out 

map:
	@$(COMPILER) $(FLAGS)	my_map_tests.cpp -o map.out 

stack:
	@$(COMPILER) $(FLAGS)	my_stack_tests.cpp -o stack.out 

clean:
	rm -f vector.out map.out stack.out
